spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/kbk_db}
spring.datasource.username=${DB_USERNAME:kbk_db}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
file.upload-root=${FILE_UPLOAD_ROOT:/mnt/attachments}
mail.queue-dir=${MAIL_QUEUE_DIR:/mnt/queue}

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.messages.encoding=UTF-8

server.port=8081
