spring.datasource.url=jdbc:mariadb://localhost:3306/kbk_db
spring.datasource.username=kbk_db
spring.datasource.password=qnrkd11609*
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
file.upload-root=/mnt/ddd/첨부파일
mail.queue-dir=/mnt/queue

server.port=8081
